/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InventarioRouteImport } from './routes/inventario'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InventarioNovoRouteImport } from './routes/inventario.novo'

const InventarioRoute = InventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventarioNovoRoute = InventarioNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => InventarioRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inventario': typeof InventarioRouteWithChildren
  '/inventario/novo': typeof InventarioNovoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inventario': typeof InventarioRouteWithChildren
  '/inventario/novo': typeof InventarioNovoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/inventario': typeof InventarioRouteWithChildren
  '/inventario/novo': typeof InventarioNovoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/inventario' | '/inventario/novo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/inventario' | '/inventario/novo'
  id: '__root__' | '/' | '/inventario' | '/inventario/novo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InventarioRoute: typeof InventarioRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/inventario': {
      id: '/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof InventarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventario/novo': {
      id: '/inventario/novo'
      path: '/novo'
      fullPath: '/inventario/novo'
      preLoaderRoute: typeof InventarioNovoRouteImport
      parentRoute: typeof InventarioRoute
    }
  }
}

interface InventarioRouteChildren {
  InventarioNovoRoute: typeof InventarioNovoRoute
}

const InventarioRouteChildren: InventarioRouteChildren = {
  InventarioNovoRoute: InventarioNovoRoute,
}

const InventarioRouteWithChildren = InventarioRoute._addFileChildren(
  InventarioRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InventarioRoute: InventarioRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
