/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InventarioIndexRouteImport } from './routes/inventario.index'
import { Route as InventarioNovoRouteImport } from './routes/inventario.novo'
import { Route as InventarioEditarIdRouteImport } from './routes/inventario.editar.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventarioIndexRoute = InventarioIndexRouteImport.update({
  id: '/inventario/',
  path: '/inventario/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventarioNovoRoute = InventarioNovoRouteImport.update({
  id: '/inventario/novo',
  path: '/inventario/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const InventarioEditarIdRoute = InventarioEditarIdRouteImport.update({
  id: '/inventario/editar/$id',
  path: '/inventario/editar/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inventario/novo': typeof InventarioNovoRoute
  '/inventario/': typeof InventarioIndexRoute
  '/inventario/editar/$id': typeof InventarioEditarIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inventario/novo': typeof InventarioNovoRoute
  '/inventario': typeof InventarioIndexRoute
  '/inventario/editar/$id': typeof InventarioEditarIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/inventario/novo': typeof InventarioNovoRoute
  '/inventario/': typeof InventarioIndexRoute
  '/inventario/editar/$id': typeof InventarioEditarIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/inventario/novo'
    | '/inventario/'
    | '/inventario/editar/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/inventario/novo' | '/inventario' | '/inventario/editar/$id'
  id:
    | '__root__'
    | '/'
    | '/inventario/novo'
    | '/inventario/'
    | '/inventario/editar/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InventarioNovoRoute: typeof InventarioNovoRoute
  InventarioIndexRoute: typeof InventarioIndexRoute
  InventarioEditarIdRoute: typeof InventarioEditarIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventario/': {
      id: '/inventario/'
      path: '/inventario'
      fullPath: '/inventario/'
      preLoaderRoute: typeof InventarioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventario/novo': {
      id: '/inventario/novo'
      path: '/inventario/novo'
      fullPath: '/inventario/novo'
      preLoaderRoute: typeof InventarioNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventario/editar/$id': {
      id: '/inventario/editar/$id'
      path: '/inventario/editar/$id'
      fullPath: '/inventario/editar/$id'
      preLoaderRoute: typeof InventarioEditarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InventarioNovoRoute: InventarioNovoRoute,
  InventarioIndexRoute: InventarioIndexRoute,
  InventarioEditarIdRoute: InventarioEditarIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
